<a href="https://colab.research.google.com/github/ugururesin/Deep_Learning_Projects/blob/main/Customization_of_Activation_and_Loss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
## Importing Libraries
import tensorflow as tf
import numpy as np

In [10]:
tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>

In [4]:
## Testing Tensorflow Library
c1 = tf.constant(2)
c2 = tf.constant(5)
tf.multiply(c1,c2)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
## Creating an Sigmoid Function
x = tf.constant(5.0)
sigmoid_val = tf.divide(1.0, tf.add(1.0, tf.exp(tf.negative(x))))
sigmoid_val

<tf.Tensor: shape=(), dtype=float32, numpy=0.9933072>

In [21]:
## Derivative Example
x = tf.constant([5.0])

with tf.GradientTape() as t:
  t.watch(x)
  y = tf.divide(1.0, tf.add(1.0, tf.exp(tf.negative(x))))

# Derivative of y with respect to the original input tensor x
dy_dx = t.gradient(y,x)
print("The sigmoid value: ", y)
print("The derivative of sigmoid: ", dy_dx)

The sigmoid value:  tf.Tensor([0.9933072], shape=(1,), dtype=float32)
The derivative of sigmoid:  tf.Tensor([0.00664806], shape=(1,), dtype=float32)
