# TensorFlow Notebook
## Fundamentals

[Uğur Üresin, PhDc.](https://github.com/ugururesin) - [uresin.ugur@gmail.com.tr](mailto:uresin.ugur@gmail.com.tr)

### Librarires

In [1]:
import tensorflow as tf

In [2]:
from tensorflow import keras

In [16]:
# TF VERSION
print(tf.__version__)

2.3.0


### Difference Between V1 & V2

**Tensorflow V1**  
msg = tf.constant('Hello, TensorFlow!')  
sess = tf.Session()  
print(sess.run(msg))  
  
**Tensorflow V2**  
msg = tf.constant('Hello, TensorFlow!')  
tf.print(msg)  

### Tensors

#### TF Constants

In [9]:
constant1 = tf.constant("Constant String")
constant1

<tf.Tensor: shape=(), dtype=string, numpy=b'Constant String'>

In [10]:
constant2 = tf.constant(1)
constant2

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [11]:
constant3 = tf.constant(1.123)
constant3

<tf.Tensor: shape=(), dtype=float32, numpy=1.123>

In [14]:
constant4 = tf.constant(True)
constant4

<tf.Tensor: shape=(), dtype=bool, numpy=True>

#### TF Variables

In [17]:
string = tf.Variable("Variable string!", tf.string)
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Variable string!'>

In [18]:
integer = tf.Variable(123, tf.int16)
integer

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>

In [19]:
floating = tf.Variable(3.14, tf.float64)
floating

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>

#### Rank/Degree and Shape of Tensors

In [26]:
rank1_tensor = tf.Variable(["sample1", "sample2", "sample3"], tf.string)

print("The rank of the tensor:", tf.rank(rank1_tensor))
print("The shape of the tensor:", rank1_tensor.shape)

The rank of the tensor: tf.Tensor(1, shape=(), dtype=int32)
The shape of the tensor: (3,)


In [27]:
rank2_tensor = tf.Variable([["sample1", "sample2"], ["ok", "nok"]], tf.string)

print("The rank of the tensor:", tf.rank(rank2_tensor))
print("The shape of the tensor:", rank2_tensor.shape)

The rank of the tensor: tf.Tensor(2, shape=(), dtype=int32)
The shape of the tensor: (2, 2)


#### Changing Shape

In [29]:
# tf.ones([x,y]) -> creates a shape [x,y] tensor full of ones

tensor1 = tf.ones([1,2,3]) 
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [30]:
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [31]:
tensor3 = tf.reshape(tensor1, [3, -1]) #-1 tells the tensor to calculate the size of the dimension in that place,
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#### Type of Tensors

**Mutable**
* Variable

**Immutable** (it's value can not be changed)
* Constants
* Placeholders
* SparseTensor

#### Getting The Value of a Tensor (Evaluation)

In [47]:
tensor1 = tf.zeros([3,2,1])
tf.print(tensor1)

[[[0]
  [0]]

 [[0]
  [0]]

 [[0]
  [0]]]
